config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

from no_mas_accidentes.users.views import user_redirect_view

urlpatterns = [
    path("", view=user_redirect_view, name="home_page"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("no_mas_accidentes.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("", include("pwa.urls")),
    path(
        "administracion/",
        include("no_mas_accidentes.administracion.urls", namespace="administracion"),
    ),
    path(
        "profesionales/",
        include("no_mas_accidentes.profesionales.urls", namespace="profesionales"),
    ),
    path("clientes/", include("no_mas_accidentes.clientes.urls", namespace="clientes")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

no_mas_accidentes/administracion/urls.py
from django.urls import path

from no_mas_accidentes.administracion.views import (
    actualizar_reporte_cliente_view,
    crear_cliente_view,
    crear_empresa_view,
    crear_profesional_view,
    descarga_contrato_base_view,
    detalle_cliente_informacion_view,
    detalle_empresa_contrato_view,
    detalle_empresa_contratos_view,
    detalle_empresa_informacion_view,
    detalle_empresa_pago_view,
    detalle_empresa_pagos_view,
    detalle_profesional_informacion_view,
    enviar_recordatorio_no_pago_view,
    home_view,
    lista_clientes_view,
    lista_empresas_view,
    lista_profesionales_view,
    lista_servicios_view,
    reporte_global_view,
)

app_name = "administracion"
urlpatterns = [
    path("home/", view=home_view, name="home"),
    path(
        "mantenedor-clientes/lista",
        view=lista_clientes_view,
        name="mantenedor_clientes_lista",
    ),
    path(
        "mantenedor-clientes/crear",
        view=crear_cliente_view,
        name="mantenedor_clientes_crear",
    ),
    path(
        "mantenedor-clientes/<int:pk>/informacion",
        view=detalle_cliente_informacion_view,
        name="mantenedor_clientes_detalle_informacion",
    ),
    path(
        "mantenedor-profesionales/lista",
        view=lista_profesionales_view,
        name="mantenedor_profesionales_lista",
    ),
    path(
        "mantenedor-profesionales/crear",
        view=crear_profesional_view,
        name="mantenedor_profesionales_crear",
    ),
    path(
        "mantenedor-profesionales/<int:pk>/informacion",
        view=detalle_profesional_informacion_view,
        name="mantenedor_profesionales_detalle_informacion",
    ),
    path(
        "mantenedor-empresas/lista",
        view=lista_empresas_view,
        name="mantenedor_empresas_lista",
    ),
    path(
        "mantenedor-empresas/crear",
        view=crear_empresa_view,
        name="mantenedor_empresas_crear",
    ),
    path(
        "mantenedor-empresas/<int:pk>/informacion",
        view=detalle_empresa_informacion_view,
        name="mantenedor_empresas_detalle_informacion",
    ),
    path(
        "mantenedor-empresas/<int:pk>/contratos",
        view=detalle_empresa_contratos_view,
        name="mantenedor_empresas_detalle_contratos",
    ),
    path(
        "mantenedor-empresas/<int:pk>/contrato/<int:contrato_id>",
        view=detalle_empresa_contrato_view,
        name="mantenedor_empresas_detalle_contrato",
    ),
    path(
        "mantenedor-empresas/<int:pk>/pagos",
        view=detalle_empresa_pagos_view,
        name="mantenedor_empresas_detalle_pagos",
    ),
    path(
        "mantenedor-empresas/<int:pk>/pagos/<int:factura_mensual_id>",
        view=detalle_empresa_pago_view,
        name="mantenedor_empresas_detalle_pago",
    ),
    path(
        "servicios/lista",
        view=lista_servicios_view,
        name="servicios_lista",
    ),
    path(
        "contratos/<int:pk>/descarga_base",
        view=descarga_contrato_base_view,
        name="descarga_contrato_base_pdf",
    ),
    path(
        "contratos/<int:pk>/enviar-recordatorio-no-pago/<int:factura_mensual_id>",
        view=enviar_recordatorio_no_pago_view,
        name="enviar_recordatorio_no_pago",
    ),
    path("reporte-global/", view=reporte_global_view, name="reporte_global"),
    path(
        "mantenedor-empresas/<int:pk>/modificar-reporte/",
        view=actualizar_reporte_cliente_view,
        name="actualizar_reporte_cliente",
    ),
]

no_mas_accidentes/clientes/urls.py
from django.urls import path

from no_mas_accidentes.clientes.views import (
    empresa_adeudada_view,
    home_view,
    modificar_multa_view,
    modificar_participantes_capacitacion_view,
    realizar_pago_view,
    recepcion_transaccion_view,
    reporte_cliente_view,
    solicitar_asesoria_emergencia_view,
    solicitar_asesoria_view,
    solicitar_capacitacion_view,
    solicitar_visita_view,
    transaccion_exitosa_view,
)

app_name = "clientes"
urlpatterns = [
    path("home/", view=home_view, name="home"),
    path("realizar-pago/", view=realizar_pago_view, name="realizar_pago"),
    path("empresa-adeudada/", view=empresa_adeudada_view, name="empresa_adeudada"),
    path(
        "transaccion-exitosa/",
        view=transaccion_exitosa_view,
        name="transaccion_exitosa",
    ),
    path(
        "recepcion-transaccion/",
        view=recepcion_transaccion_view,
        name="recepcion_transaccion",
    ),
    path("reporte-historico/", view=reporte_cliente_view, name="reporte_cliente"),
    path(
        "solicitar-asesoria-emergencia/",
        view=solicitar_asesoria_emergencia_view,
        name="solicitar_asesoria_emergencia",
    ),
    path(
        "solicitar-capacitacion/",
        view=solicitar_capacitacion_view,
        name="solicitar_capacitacion",
    ),
    path(
        "capacitacion/<int:pk>/modificar-participantes/",
        view=modificar_participantes_capacitacion_view,
        name="modificar_participantes_capacitacion",
    ),
    path(
        "solicitar-visita/",
        view=solicitar_visita_view,
        name="solicitar_visita",
    ),
    path(
        "solicitar-asesoria/",
        view=solicitar_asesoria_view,
        name="solicitar_asesoria",
    ),
    path(
        "asesoria/<int:pk>/modificar-multa",
        view=modificar_multa_view,
        name="asesoria_modificar_multa",
    ),
]

no_mas_accidentes/profesionales/urls.py
from django.urls import path

from no_mas_accidentes.profesionales.views import (
    actualizar_actividad_de_mejora_view,
    actualizar_asesoria_emergencia_view,
    actualizar_asesoria_view,
    actualizar_asistencia_capacitacion_view,
    actualizar_capacitacion_view,
    actualizar_checklist_view,
    actualizar_visita_view,
    crear_o_actualizar_checklist_base_view,
    detalle_empresa_informacion_view,
    home_view,
    lista_actividades_mejora_view,
    lista_empresas_asignadas_view,
    lista_servicios_asignados_view,
    revisar_actividad_de_mejora_view,
)

app_name = "profesionales"
urlpatterns = [
    path("home/", view=home_view, name="home"),
    path(
        "empresas-asignadas/lista",
        view=lista_empresas_asignadas_view,
        name="empresas_asignadas_lista",
    ),
    path(
        "empresas-asignadas/<int:pk>/informacion",
        view=detalle_empresa_informacion_view,
        name="empresas_asignadas_detalle_informacion",
    ),
    path(
        "empresas-asignadas/<int:pk>/checklist_base/",
        view=crear_o_actualizar_checklist_base_view,
        name="empresas_asignadas_crear_o_actualizar_checklist_base",
    ),
    path(
        "empresas-asignadas/<int:pk>/actividades-mejora/",
        view=lista_actividades_mejora_view,
        name="empresas_asignadas_actividades_de_mejora",
    ),
    path(
        "servicios/lista",
        view=lista_servicios_asignados_view,
        name="servicios_asignados_lista",
    ),
    path(
        "asesoria-emergencia/<int:pk>/actualizar",
        view=actualizar_asesoria_emergencia_view,
        name="asesoria_emergencia_actualizar",
    ),
    path(
        "capacitacion/<int:pk>/actualizar",
        view=actualizar_capacitacion_view,
        name="capacitacion_actualizar",
    ),
    path(
        "capacitacion/<int:pk>/asistencia",
        view=actualizar_asistencia_capacitacion_view,
        name="capacitacion_actualizar_asistencia",
    ),
    path(
        "visita/<int:pk>/actualizar",
        view=actualizar_visita_view,
        name="visita_actualizar",
    ),
    path(
        "visita/<int:pk>/checklist",
        view=actualizar_checklist_view,
        name="visita_actualizar_checklist",
    ),
    path(
        "visita/<int:pk>/actividad-de-mejora",
        view=actualizar_actividad_de_mejora_view,
        name="visita_actualizar_actividad_mejora",
    ),
    path(
        "asesoria/<int:pk>/actualizar",
        view=actualizar_asesoria_view,
        name="asesoria_actualizar",
    ),
    path(
        "actividad-de-mejora/<int:pk>/revisar/<str:realizado>",
        view=revisar_actividad_de_mejora_view,
        name="revisar_actividad_mejora",
    ),
]

no_mas_accidentes/users/urls.py
from django.urls import path

from no_mas_accidentes.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

no_mas_accidentes/servicios/forms.py
from collections import Counter

from django import forms
from django.contrib import messages
from django.core.validators import MaxValueValidator, MinValueValidator

from no_mas_accidentes.clientes.models import FacturaMensual
from no_mas_accidentes.servicios.models import ChecklistBase


class CrearOActualizarChecklistBaseForm(forms.Form):
    numero_de_items = forms.IntegerField(
        widget=forms.HiddenInput(),
        validators=[MinValueValidator(3), MaxValueValidator(15)],
    )

    def __init__(self, *args, **kwargs):
        numero_de_items = kwargs.pop("numero_de_items", 3)
        self.id_empresa = kwargs.pop("id_empresa")
        self.request = kwargs.pop("request")
        super().__init__(*args, **kwargs)
        self.fields["numero_de_items"].initial = numero_de_items
        for index in range(int(numero_de_items)):
            self.fields[f"item_{index+1}"] = forms.CharField(
                min_length=10, max_length=256
            )

    def clean(self):
        cleaned_data = self.cleaned_data
        preguntas = list(self.cleaned_data.values())
        items_duplicados = [k for k, v in Counter(preguntas).items() if v > 1]

        if items_duplicados:
            cleaned_data_con_items_duplicados = cleaned_data.copy()
            for k, v in cleaned_data_con_items_duplicados.items():
                if v in items_duplicados:
                    self.add_error(field=k, error="Este item está duplicado")
            messages.warning(
                request=self.request,
                message=f"Existen items duplicados en el checklist: {items_duplicados}",
            )
        return cleaned_data

    def save(self, commit: bool = True):
        cleaned_data = self.cleaned_data.copy()
        cleaned_data.pop("numero_de_items")
        items_nuevos = {
            field: False for key, field in cleaned_data.items() if "item" in key
        }
        if self.initial:
            # actualizado
            checklist = ChecklistBase.objects.get(empresa_id=self.id_empresa)
            if checklist.items == items_nuevos:
                messages.info(
                    request=self.request,
                    message="Los items a actualizar son iguales a los anteriores, no se ha actualizado el checklist.",
                )
                return
            messages.success(
                request=self.request, message="Se ha actualizado el checklist"
            )
            factura_mensual: FacturaMensual = FacturaMensual.objects.last()
            factura_mensual.agregar_nueva_modificacion_checklist(
                checklist_base=checklist, generado_por=self.request.user.id
            )
            checklist.items = items_nuevos
            checklist.save()
        else:
            # creado
            checklist = ChecklistBase(items=items_nuevos, empresa_id=self.id_empresa)
            messages.success(request=self.request, message="Se ha creado el checklist")
        checklist.save()

no_mas_accidentes/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

no_mas_accidentes/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

no_mas_accidentes/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        if self.request.user.is_superuser:
            return reverse("admin:index", kwargs={})
        nombre_grupo = self.request.user.groups.first().name
        pagina_por_grupo = {
            "cliente": "clientes:home",
            "profesional": "profesionales:home",
            "administrador": "administracion:home",
        }
        pagina = pagina_por_grupo[nombre_grupo]
        return reverse(pagina, kwargs={})


user_redirect_view = UserRedirectView.as_view()

no_mas_accidentes/templates/administracion/base.html
{% extends 'partials/base.html' %}
{% load static %}

{% block sidebar %}

<div class="topnav">
    <div class="container-fluid">
        <nav class="navbar navbar-light navbar-expand-lg topnav-menu">

            <div class="collapse navbar-collapse" id="topnav-menu-content">
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle arrow-none" href="{% url 'administracion:home' %}" id="topnav-home" role="button">
                            <i class="bx bx-home-circle me-2"></i><span key="t-dashboards">Home</span>
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle arrow-none" href="#" id="topnav-mantenedores" role="button">
                            <i class="bx bx-edit-alt me-2"></i><span key="t-dashboards">Mantenedores</span>
                            <div class="arrow-down"></div>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="topnav-mantenedores">
                            <a href="{% url 'administracion:mantenedor_clientes_lista' %}" class="dropdown-item"><i class="bx bx-male me-2"></i>Clientes</a>
                            <a href="{% url 'administracion:mantenedor_empresas_lista' %}" class="dropdown-item"><i class="bx bxs-factory me-2"></i>Empresas</a>
                            <a href="{% url 'administracion:mantenedor_profesionales_lista' %}" class="dropdown-item"><i class="bx bx-street-view me-2"></i>Profesionales</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle arrow-none" href="{% url 'administracion:servicios_lista' %}" id="topnav-home" role="button">
                            <i class="fas fa-chalkboard-teacher me-2"></i><span key="t-dashboards">Actividades</span>
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle arrow-none" href="{% url 'administracion:reporte_global' %}" id="topnav-home" role="button">
                            <i class="bx bxs-report me-2"></i><span key="t-dashboards">Reporte global</span>
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</div>
{%endblock%}

no_mas_accidentes/templates/administracion/crear_cliente.html
{% extends 'administracion/base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block contents %}
<div class="row">
    <div class="col-lg-12">
        <div class="container">
            <div class="card shadow-sm">
                <h5 class="card-header ">Crear cliente</h5>
                    <div class="card-body col-lg-12 mt-5">
                        <form action="" method="post">
                            {% csrf_token %}

                            {% for error in form.non_field_errors %}
                                {{ error }}
                            {% endfor %}

                            <div class="row">
                                <div class="col-lg-4">
                                {% for field in form %}
                                     <div class="mb-3">
                                        <div>{{ field|as_crispy_field }}</div>
                                    </div>
                                    {% if forloop.last %}
                                       </div>
                                    {% else %}
                                       {% if forloop.counter|divisibleby:"2" %}
                                        </div>
                                        <div class="col-lg-4">
                                       {% endif %}
                                    {% endif %}
                                {% endfor %}
                            </div>

                            <div class="d-flex flex-wrap gap-4 justify-content-end">
                                <input type="submit" class="btn btn-primary waves-effect waves-light" value="Crear nuevo">
                                <input type="submit" class="btn btn-danger waves-effect waves-light" onclick="window.location='{% url 'administracion:mantenedor_clientes_lista' %}'; return false;" value="Cancelar">
                            </div>
                        </form>
                    </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

no_mas_accidentes/templates/administracion/crear_empresa.html
{% extends 'administracion/base.html' %}

{% load static %}
{% load crispy_forms_tags %}
{% block contents %}
<div class="row">
    <div class="col-lg-12">
        <div class="container">
            <div class="card shadow-sm">
                <h5 class="card-header ">Crear empresa</h5>
                <div class="card-body col-lg-12 mt-5">
                    <form action="" method="post">
                        {% csrf_token %}

                        {% for error in form.non_field_errors %}
                            {{ error }}
                        {% endfor %}

                        <div class="row">
                            <div class="col-lg-4">
                            {% for field in form %}
                                 <div class="mb-3">
                                    <div>{{ field|as_crispy_field }}</div>
                                </div>
                                {% if forloop.last %}
                                   </div>
                                {% else %}
                                   {% if forloop.counter|divisibleby:"2" %}
                                    </div>
                                    <div class="col-lg-4">
                                   {% endif %}
                                {% endif %}
                            {% endfor %}
                        </div>

                        <div class="d-flex flex-wrap gap-4 justify-content-end">
                            <input type="submit" class="btn btn-primary waves-effect waves-light" value="Crear nuevo">
                            <input type="submit" class="btn btn-danger waves-effect waves-light" onclick="window.location='{% url 'administracion:mantenedor_empresas_lista' %}'; return false;" value="Cancelar">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

no_mas_accidentes/templates/administracion/lista_clientes.html
{% extends 'administracion/base.html' %}

{% load static %}

{% block contents %}
<div class="row">
    <div class="col-lg-12">
      <div class="row mb-2">
            <div class="col-sm-12">
                  <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                      <h4 class="mb-sm-0 font-size-18">Mantenedor de clientes</h4>
                  </div>
            </div><!-- end col-->
        </div>
        <div class="row mb-2">
            <div class="col-sm-4">
                <form method="get" action="{% url 'administracion:mantenedor_clientes_lista' %}">
                    <div class="search-box me-2 mb-2 d-inline-block">
                        <div class="position-relative">
                            <input name="filtro_rut" type="text" class="form-control" value="{{filtro_rut}}" placeholder="Ingrese rut a buscar">
                            <i class="bx bx-search-alt search-icon"></i>
                        </div>
                    </div>
                    <input class="btn btn-primary waves-effect waves-light" type="submit" name="submit" value="Buscar"/>
                </form>
            </div>
            <div class="col-sm-8">
                <div class="text-sm-end">
                    <a type="button" class="btn btn-success btn-rounded waves-effect waves-light mb-2 me-2" href="{% url 'administracion:mantenedor_clientes_crear' %}"><i class="mdi mdi-plus me-1"></i>Crear nuevo cliente</a>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table align-middle table-nowrap table-hover">
                        <thead class="table-light">
                            <tr>
                                <th scope="col" style="width: 70px;">#</th>
                                <th scope="col">RUT</th>
                                <th scope="col">USUARIO</th>
                                <th scope="col">EMAIL</th>
                                <th scope="col">NOMBRE</th>
                                <th scope="col">¿ESTÁ ACTIVO?</th>
                                <th scope="col">CREADO EN</th>
                                <th scope="col">EMPRESA</th>
                                <th scope="col">ACCIONES</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for cliente in page_obj %}
                            <tr>
                                <td>{{ cliente.id }}</td>
                                <td>{{ cliente.rut }}</td>
                                <td>
                                    <h5 class="font-size-14 mb-1"><a href="javascript: void(0);" class="text-dark">{{ cliente.username }}</a></h5>
                                </td>
                                <td>{{ cliente.email }}</td>
                                <td>
                                   {{ cliente.name }}
                                </td>
                                <td>
                                    {% if cliente.is_active %}
                                        <p class="badge badge-soft-primary font-size-11 m-1">SI</p>
                                    {% else %}
                                        <p class="badge badge-soft-danger font-size-11 m-1">NO</p>
                                    {% endif %}
                                </td>
                                <td>
                                    {{ cliente.date_joined|date:"SHORT_DATETIME_FORMAT" }}
                                </td>
                                <td>
                                    {% if cliente.empresa %}
                                      {{ cliente.empresa }}
                                    {% else %}
                                      SIN ASIGNAR
                                    {% endif %}
                                </td>
                                <td>
                                    <ul class="list-inline font-size-20 contact-links mb-0">
                                        <li class="list-inline-item px-2">
                                            <a href="{% url 'administracion:mantenedor_clientes_detalle_informacion' pk=cliente.pk %}" title="Detalles"><i class="bx bx-user-circle"></i></a>
                                        </li>
                                        {% if cliente.empresa %}
                                        <li class="list-inline-item px-2">
                                            <a href="{% url 'administracion:mantenedor_empresas_detalle_informacion' pk=cliente.empresa_id %}" title="Ver empresa"><i class="bx bxs-business"></i></a>
                                        </li>
                                        {% endif %}
                                    </ul>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <ul class="pagination justify-content-center mt-4">
                            {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a href="?page={{ page_obj.previous_page_number }}" class="page-link"><i class="mdi mdi-chevron-left"></i></a>
                            </li>
                            {% endif %}
                            <li class="page-item">
                                <a class="page-link">{{ page_obj.number }} de {{page_obj.paginator.num_pages }}</a>
                            </li>
                            {% if page_obj.has_next %}
                            <li class="page-item">
                                <a href="?page={{ page_obj.next_page_number }}" class="page-link"><i class="mdi mdi-chevron-right"></i></a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}