config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

from no_mas_accidentes.users.views import user_redirect_view

urlpatterns = [
    path("", view=user_redirect_view, name="home_page"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("no_mas_accidentes.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("", include("pwa.urls")),
    path(
        "administracion/",
        include("no_mas_accidentes.administracion.urls", namespace="administracion"),
    ),
    path(
        "profesionales/",
        include("no_mas_accidentes.profesionales.urls", namespace="profesionales"),
    ),
    path("clientes/", include("no_mas_accidentes.clientes.urls", namespace="clientes")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

no_mas_accidentes/clientes/urls.py
from django.urls import path

from no_mas_accidentes.clientes.views import (
    empresa_adeudada_view,
    home_view,
    modificar_multa_view,
    modificar_participantes_capacitacion_view,
    realizar_pago_view,
    recepcion_transaccion_view,
    reporte_cliente_view,
    solicitar_asesoria_emergencia_view,
    solicitar_asesoria_view,
    solicitar_capacitacion_view,
    solicitar_visita_view,
    transaccion_exitosa_view,
)

app_name = "clientes"
urlpatterns = [
    path("home/", view=home_view, name="home"),
    path("realizar-pago/", view=realizar_pago_view, name="realizar_pago"),
    path("empresa-adeudada/", view=empresa_adeudada_view, name="empresa_adeudada"),
    path(
        "transaccion-exitosa/",
        view=transaccion_exitosa_view,
        name="transaccion_exitosa",
    ),
    path(
        "recepcion-transaccion/",
        view=recepcion_transaccion_view,
        name="recepcion_transaccion",
    ),
    path("reporte-historico/", view=reporte_cliente_view, name="reporte_cliente"),
    path(
        "solicitar-asesoria-emergencia/",
        view=solicitar_asesoria_emergencia_view,
        name="solicitar_asesoria_emergencia",
    ),
    path(
        "solicitar-capacitacion/",
        view=solicitar_capacitacion_view,
        name="solicitar_capacitacion",
    ),
    path(
        "capacitacion/<int:pk>/modificar-participantes/",
        view=modificar_participantes_capacitacion_view,
        name="modificar_participantes_capacitacion",
    ),
    path(
        "solicitar-visita/",
        view=solicitar_visita_view,
        name="solicitar_visita",
    ),
    path(
        "solicitar-asesoria/",
        view=solicitar_asesoria_view,
        name="solicitar_asesoria",
    ),
    path(
        "asesoria/<int:pk>/modificar-multa",
        view=modificar_multa_view,
        name="asesoria_modificar_multa",
    ),
]

no_mas_accidentes/profesionales/urls.py
from django.urls import path

from no_mas_accidentes.profesionales.views import (
    actualizar_actividad_de_mejora_view,
    actualizar_asesoria_emergencia_view,
    actualizar_asesoria_view,
    actualizar_asistencia_capacitacion_view,
    actualizar_capacitacion_view,
    actualizar_checklist_view,
    actualizar_visita_view,
    crear_o_actualizar_checklist_base_view,
    detalle_empresa_informacion_view,
    home_view,
    lista_actividades_mejora_view,
    lista_empresas_asignadas_view,
    lista_servicios_asignados_view,
    revisar_actividad_de_mejora_view,
)

app_name = "profesionales"
urlpatterns = [
    path("home/", view=home_view, name="home"),
    path(
        "empresas-asignadas/lista",
        view=lista_empresas_asignadas_view,
        name="empresas_asignadas_lista",
    ),
    path(
        "empresas-asignadas/<int:pk>/informacion",
        view=detalle_empresa_informacion_view,
        name="empresas_asignadas_detalle_informacion",
    ),
    path(
        "empresas-asignadas/<int:pk>/checklist_base/",
        view=crear_o_actualizar_checklist_base_view,
        name="empresas_asignadas_crear_o_actualizar_checklist_base",
    ),
    path(
        "empresas-asignadas/<int:pk>/actividades-mejora/",
        view=lista_actividades_mejora_view,
        name="empresas_asignadas_actividades_de_mejora",
    ),
    path(
        "servicios/lista",
        view=lista_servicios_asignados_view,
        name="servicios_asignados_lista",
    ),
    path(
        "asesoria-emergencia/<int:pk>/actualizar",
        view=actualizar_asesoria_emergencia_view,
        name="asesoria_emergencia_actualizar",
    ),
    path(
        "capacitacion/<int:pk>/actualizar",
        view=actualizar_capacitacion_view,
        name="capacitacion_actualizar",
    ),
    path(
        "capacitacion/<int:pk>/asistencia",
        view=actualizar_asistencia_capacitacion_view,
        name="capacitacion_actualizar_asistencia",
    ),
    path(
        "visita/<int:pk>/actualizar",
        view=actualizar_visita_view,
        name="visita_actualizar",
    ),
    path(
        "visita/<int:pk>/checklist",
        view=actualizar_checklist_view,
        name="visita_actualizar_checklist",
    ),
    path(
        "visita/<int:pk>/actividad-de-mejora",
        view=actualizar_actividad_de_mejora_view,
        name="visita_actualizar_actividad_mejora",
    ),
    path(
        "asesoria/<int:pk>/actualizar",
        view=actualizar_asesoria_view,
        name="asesoria_actualizar",
    ),
    path(
        "actividad-de-mejora/<int:pk>/revisar/<str:realizado>",
        view=revisar_actividad_de_mejora_view,
        name="revisar_actividad_mejora",
    ),
]

no_mas_accidentes/users/urls.py
from django.urls import path

from no_mas_accidentes.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

no_mas_accidentes/administracion/views.py
import itertools

from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.messages.views import SuccessMessageMixin
from django.core.files.storage import FileSystemStorage
from django.db.models import Q
from django.db.models.aggregates import Sum
from django.db.models.functions import TruncMonth
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    CreateView,
    ListView,
    RedirectView,
    TemplateView,
    UpdateView,
)
from rest_framework.decorators import api_view

from no_mas_accidentes.administracion.business_logic.contrato import (
    generar_pdf_contrato_base,
)
from no_mas_accidentes.administracion.constants import (
    INFORMACION_EMPRESA_PREVENCION_CHILE,
    app_name,
)
from no_mas_accidentes.administracion.forms import (
    ActualizarContratoForm,
    ActualizarDetalleClienteForm,
    ActualizarDetalleEmpresaForm,
    ActualizarDetalleProfesionalForm,
    CrearClienteForm,
    CrearEmpresaForm,
    CrearProfesionalForm,
)
from no_mas_accidentes.administracion.mixins import (
    EsAdministradorMixin,
    PassRequestToFormViewMixin,
    usuario_es_administrador,
)
from no_mas_accidentes.administracion.tasks import enviar_recordatorio_no_pago
from no_mas_accidentes.clientes.models import Contrato, Empresa, FacturaMensual
from no_mas_accidentes.profesionales.models import Profesional
from no_mas_accidentes.servicios.business_logic.reportes import (
    actualizar_reporte_cliente,
)
from no_mas_accidentes.servicios.constants import TIPOS_DE_SERVICIOS
from no_mas_accidentes.servicios.models import Servicio
from no_mas_accidentes.users.models import User


class HomeView(EsAdministradorMixin, TemplateView):
    template_name = f"{app_name}/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["num_clientes"] = User.objects.filter(groups__name="cliente").count()
        context["num_empresas"] = Empresa.objects.all().count()
        context["num_profesionales"] = Profesional.objects.all().count()
        return context


home_view = HomeView.as_view()


# -- Mantenedor de Clientes --
class ListaClientesView(EsAdministradorMixin, ListView):
    queryset = User.objects.filter(groups__name="cliente").all()
    fields = "__all__"
    success_url = reverse_lazy(f"{app_name}:mantenedor_clientes_lista")
    ordering = "id"
    paginate_by = 10
    template_name = f"{app_name}/lista_clientes.html"

    def get_queryset(self):
        filtro_rut = self.request.GET.get("filtro_rut")
        queryset = self.queryset.order_by(self.ordering)
        if filtro_rut:
            rut_a_buscar = str(filtro_rut).upper()
            queryset = queryset.filter(
                Q(rut=rut_a_buscar) | Q(empresa__rut=rut_a_buscar)
            )
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filtro_rut"] = self.request.GET.get("filtro_rut", "")
        return context


class CrearClienteView(
    EsAdministradorMixin, PassRequestToFormViewMixin, SuccessMessageMixin, CreateView
):
    template_name = f"{app_name}/crear_cliente.html"
    form_class = CrearClienteForm
    success_url = reverse_lazy(f"{app_name}:mantenedor_clientes_lista")

    def get_success_message(self, cleaned_data):
        return (
            f"Cliente {self.object.id} - {self.object.email} creado satisfactoriamente"
        )


class DetalleClienteInformacionView(
    EsAdministradorMixin, SuccessMessageMixin, UpdateView
):
    template_name = f"{app_name}/detalle_cliente/informacion.html"
    form_class = ActualizarDetalleClienteForm
    queryset = User.objects.filter(groups__name="cliente").all()

    def get_success_url(self) -> str:
        return reverse_lazy(
            f"{app_name}:mantenedor_clientes_detalle_informacion",
            kwargs={"pk": self.object.pk},
        )

    def get_success_message(self, cleaned_data):
        return f"Cliente {self.object.id} - {self.object.email} actualizado satisfactoriamente"


lista_clientes_view = ListaClientesView.as_view()
crear_cliente_view = CrearClienteView.as_view()
detalle_cliente_informacion_view = DetalleClienteInformacionView.as_view()


# -- Mantenedor de profesionales --


class ListaProfesionalesView(EsAdministradorMixin, ListView):
    queryset = User.objects.filter(groups__name="profesional").all()
    fields = "__all__"
    success_url = reverse_lazy(f"{app_name}:mantenedor_profesionales_lista")
    ordering = "id"
    paginate_by = 10
    template_name = f"{app_name}/lista_profesionales.html"

    def get_queryset(self):
        filtro_rut = self.request.GET.get("filtro_rut")
        queryset = self.queryset.order_by(self.ordering)
        if filtro_rut:
            rut_a_buscar = str(filtro_rut).upper()
            queryset = queryset.filter(rut=rut_a_buscar)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filtro_rut"] = self.request.GET.get("filtro_rut", "")
        return context


class CrearProfesionalView(
    EsAdministradorMixin, PassRequestToFormViewMixin, SuccessMessageMixin, CreateView
):
    template_name = f"{app_name}/crear_profesional.html"
    form_class = CrearProfesionalForm
    success_url = reverse_lazy(f"{app_name}:mantenedor_profesionales_lista")

    def get_success_message(self, cleaned_data):
        return f"Profesional {self.object.id} - {self.object.email} creado satisfactoriamente"


class DetalleProfesionalInformacionView(
    EsAdministradorMixin, SuccessMessageMixin, UpdateView
):
    template_name = f"{app_name}/detalle_profesional/informacion.html"
    form_class = ActualizarDetalleProfesionalForm
    queryset = User.objects.filter(groups__name="profesional").all()

    def get_success_url(self) -> str:
        return reverse_lazy(
            f"{app_name}:mantenedor_profesionales_detalle_informacion",
            kwargs={"pk": self.object.pk},
        )

    def get_success_message(self, cleaned_data):
        return f"Profesional {self.object.id} - {self.object.email} actualizado satisfactoriamente"


lista_profesionales_view = ListaProfesionalesView.as_view()
crear_profesional_view = CrearProfesionalView.as_view()
detalle_profesional_informacion_view = DetalleProfesionalInformacionView.as_view()


# -- Mantenedor de empresas --


class ListaEmpresasView(EsAdministradorMixin, ListView):
    queryset = Empresa.objects.all()
    fields = "__all__"
    success_url = reverse_lazy(f"{app_name}:mantenedor_empresas_lista")
    ordering = "id"
    paginate_by = 10
    template_name = f"{app_name}/lista_empresas.html"

    def get_queryset(self):
        filtro_rut = self.request.GET.get("filtro_rut")
        queryset = self.queryset.order_by(self.ordering)
        if filtro_rut:
            rut_a_buscar = str(filtro_rut).upper()
            queryset = queryset.filter(rut=rut_a_buscar)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filtro_rut"] = self.request.GET.get("filtro_rut", "")
        return context


class CrearEmpresaView(
    EsAdministradorMixin, PassRequestToFormViewMixin, SuccessMessageMixin, CreateView
):
    template_name = f"{app_name}/crear_empresa.html"
    form_class = CrearEmpresaForm
    success_url = reverse_lazy(f"{app_name}:mantenedor_empresas_lista")

    def get_success_message(self, cleaned_data):
        return (
            f"Empresa {self.object.id} - {self.object.nombre} creada satisfactoriamente"
        )


class DetalleEmpresaInformacionView(
    EsAdministradorMixin, SuccessMessageMixin, UpdateView
):
    template_name = f"{app_name}/detalle_empresa/informacion.html"
    form_class = ActualizarDetalleEmpresaForm
    queryset = Empresa.objects.all()

    def get_success_url(self) -> str:
        return reverse_lazy(
            f"{app_name}:mantenedor_empresas_detalle_informacion",
            kwargs={"pk": self.object.pk},
        )

    def get_success_message(self, cleaned_data):
        return f"Empresa {self.object.id} - {self.object.nombre} actualizada satisfactoriamente"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["empresa"] = self.object
        return context


class DetalleEmpresaContratosView(EsAdministradorMixin, ListView):
    queryset = Contrato.objects.all()
    fields = "__all__"
    success_url = reverse_lazy(f"{app_name}:mantenedor_empresas_detalle_contratos")
    ordering = "id"
    paginate_by = 10
    template_name = f"{app_name}/detalle_empresa/contratos.html"

    def get_queryset(self):
        queryset = self.queryset.order_by(self.ordering)
        # filtrar por PK de empresa
        queryset = queryset.filter(empresa_id=self.kwargs["pk"])
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        empresa = Empresa.objects.get(pk=self.kwargs["pk"])
        context["empresa"] = empresa
        return context


class DetalleEmpresaContratoView(EsAdministradorMixin, SuccessMessageMixin, UpdateView):
    template_name = f"{app_name}/detalle_empresa/detalle_contrato.html"
    form_class = ActualizarContratoForm
    queryset = Contrato.objects.all()

    def get_success_url(self) -> str:
        return reverse_lazy(
            f"{app_name}:mantenedor_empresas_detalle_contratos",
            kwargs={"pk": self.kwargs["pk"]},
        )

    def get_success_message(self, cleaned_data):
        return "Contrato cargado satisfactoriamente"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["empresa"] = self.object
        return context

    def get_object(self):

no_mas_accidentes/templates/profesionales/base.html
{% extends 'partials/base.html' %}
{% load static %}

{% block sidebar %}

<div class="topnav">
    <div class="container-fluid">
        <nav class="navbar navbar-light navbar-expand-lg topnav-menu">

            <div class="collapse navbar-collapse" id="topnav-menu-content">
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle arrow-none" href="{% url 'profesionales:home' %}" id="topnav-home" role="button">
                            <i class="bx bx-home-circle me-2"></i><span key="t-dashboards">Home</span>
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle arrow-none" href="{% url 'profesionales:empresas_asignadas_lista' %}" id="topnav-home" role="button">
                            <i class="bx bxs-factory me-2"></i><span key="t-dashboards">Empresas asignadas</span>
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle arrow-none" href="{% url 'profesionales:servicios_asignados_lista' %}" id="topnav-home" role="button">
                            <i class="fas fa-chalkboard-teacher me-2"></i><span key="t-dashboards">Actividades asignadas</span>
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</div>
{%endblock%}

no_mas_accidentes/templates/profesionales/lista_servicios_asignados.html
{% extends 'profesionales/base.html' %}

{% load static %}

{% block contents %}
<div class="row">
    <div class="col-lg-12">
      <div class="row mb-2">
            <div class="col-sm-12">
                  <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                      <h4 class="mb-sm-0 font-size-18">Actividades asignadas</h4>
                  </div>
            </div><!-- end col-->
        </div>
        <div class="row mb-2">
            <div class="col-sm-4">
                <form method="get" action="{% url 'profesionales:servicios_asignados_lista' %}">
                    <div class="search-box me-2 mb-2 d-inline-block">
                        <div class="position-relative">
                            <input name="filtro_rut" type="text" class="form-control" value="{{filtro_rut}}" placeholder="Ingrese rut a buscar">
                            <i class="bx bx-search-alt search-icon"></i>
                        </div>
                    </div>
                    <input class="btn btn-primary waves-effect waves-light" type="submit" name="submit" value="Buscar"/>
                </form>
            </div>
            <div class="col-sm-4">
                <form method="get" action="{% url 'profesionales:servicios_asignados_lista' %}">
                    <div class="search-box me-2 mb-2 d-inline-block">
                        <div class="position-relative">
                            <select class="form-select" name="filtro_empresa_seleccionada">
                                <option value="" selected>Seleccione empresa a buscar</option>
                                {% for empresa in filtro_empresas %}
                                <option value="{{ empresa.id }}" {% if empresa.id == filtro_empresa_seleccionada %}selected{% endif %}>{{ empresa }}</option>
                                {% endfor %}
                            </select>
<!--                            <i class="bx bx-search-alt search-icon"></i>-->
                        </div>
                    </div>
                    <input class="btn btn-primary waves-effect waves-light" type="submit" name="submit" value="Buscar"/>
                </form>
            </div>
            <div class="col-sm-4">
                <form method="get" action="{% url 'profesionales:servicios_asignados_lista' %}">
                    <div class="search-box me-2 mb-2 d-inline-block">
                        <div class="position-relative">
                            <select class="form-select" name="filtro_tipo_seleccionado">
                                <option value="" selected>Seleccione tipo a buscar</option>
                                {% for tipo in filtro_tipos %}
                                <option value="{{ tipo }}" {% if tipo == filtro_tipo_seleccionado %}selected{% endif %}>{{ tipo }}</option>
                                {% endfor %}
                            </select>
<!--                            <i class="bx bx-search-alt search-icon"></i>-->
                        </div>
                    </div>
                    <input class="btn btn-primary waves-effect waves-light" type="submit" name="submit" value="Buscar"/>
                </form>
            </div>
        </div>
      <div class="row mb-2">
            <div class="col-sm-4">
                <form method="get" action="{% url 'profesionales:servicios_asignados_lista' %}">
                    <div class="search-box me-2 mb-2 d-inline-block">
                        <div class="position-relative">
                            <select class="form-select" name="filtro_es_realizado">
                                <option value="" selected>Seleccione estado a buscar</option>
                                <option value="PENDIENTE" {% if 'PENDIENTE' == filtro_es_realizado %}selected{% endif %}>PENDIENTE</option>
                                <option value="REALIZADA" {% if 'REALIZADA' == filtro_es_realizado %}selected{% endif %}>REALIZADA</option>
                            </select>
<!--                            <i class="bx bx-search-alt search-icon"></i>-->
                        </div>
                    </div>
                    <input class="btn btn-primary waves-effect waves-light" type="submit" name="submit" value="Buscar"/>
                </form>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table align-middle table-nowrap table-hover">
                        <thead class="table-light">
                            <tr>
                                <th scope="col" style="width: 70px;">#</th>
                                <th scope="col">AGENDADO PARA</th>
                                <th scope="col">TIPO</th>
                                <th scope="col">EMPRESA</th>
                                <th scope="col">PROFESIONAL</th>
                                <th scope="col">REALIZADO EN</th>
                                <th scope="col">DURACION</th>
                                <th scope="col">ACCIONES</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for servicio in page_obj %}
                            <tr>
                                <td>{{ servicio.id }}</td>
                                <td>{{ servicio.agendado_para|date:"SHORT_DATETIME_FORMAT" }}</td>
                                <td>{{ servicio.tipo }}</td>
                                <td>{{ servicio.empresa }}</td>
                                <td>{{ servicio.profesional }}</td>
                                <td>{{ servicio.realizado_en|date:"SHORT_DATETIME_FORMAT" }}</td>
                                <td>{{ servicio.duracion }}</td>
                                <td>
                                    <ul class="list-inline font-size-20 contact-links mb-0">
                                        <li class="list-inline-item px-2">
                                            {% if servicio.tipo == "ASESORIA EMERGENCIA" %}
                                                <a href="{% url 'profesionales:asesoria_emergencia_actualizar' pk=servicio.pk %}" title="Editar asesoría de emergencia"><i class="bx bx bxs-edit"></i>
                                            </a>
                                            {% elif servicio.tipo == "CAPACITACION" %}
                                                <a href="{% url 'profesionales:capacitacion_actualizar' pk=servicio.pk %}" title="Editar capacitación"><i class="bx bx bxs-edit"></i>
                                            </a>
                                            {% elif servicio.tipo == "VISITA" %}
                                                <a href="{% url 'profesionales:visita_actualizar' pk=servicio.pk %}" title="Editar visita"><i class="bx bx bxs-edit"></i>
                                            </a>
                                            {% elif servicio.tipo == "ASESORIA FISCALIZACION" %}
                                                <a href="{% url 'profesionales:asesoria_actualizar' pk=servicio.pk %}" title="Editar visita"><i class="bx bx bxs-edit"></i>
                                            </a>
                                            {% endif %}
                                        </li>
                                        <li class="list-inline-item px-2">
                                            <a href="{% url 'profesionales:empresas_asignadas_detalle_informacion' pk=servicio.empresa.pk %}" title="Ver empresa"><i class="bx bx bxs-business"></i></a>
                                        </li>
                                    </ul>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <ul class="pagination justify-content-center mt-4">
                            {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a href="?page={{ page_obj.previous_page_number }}" class="page-link"><i class="mdi mdi-chevron-left"></i></a>
                            </li>
                            {% endif %}
                            <li class="page-item">
                                <a class="page-link">{{ page_obj.number }} de {{page_obj.paginator.num_pages }}</a>
                            </li>
                            {% if page_obj.has_next %}
                            <li class="page-item">
                                <a href="?page={{ page_obj.next_page_number }}" class="page-link"><i class="mdi mdi-chevron-right"></i></a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}