config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

from no_mas_accidentes.users.views import user_redirect_view

urlpatterns = [
    path("", view=user_redirect_view, name="home_page"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("no_mas_accidentes.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("", include("pwa.urls")),
    path(
        "administracion/",
        include("no_mas_accidentes.administracion.urls", namespace="administracion"),
    ),
    path(
        "profesionales/",
        include("no_mas_accidentes.profesionales.urls", namespace="profesionales"),
    ),
    path("clientes/", include("no_mas_accidentes.clientes.urls", namespace="clientes")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

no_mas_accidentes/clientes/urls.py
from django.urls import path

from no_mas_accidentes.clientes.views import (
    empresa_adeudada_view,
    home_view,
    modificar_multa_view,
    modificar_participantes_capacitacion_view,
    realizar_pago_view,
    recepcion_transaccion_view,
    reporte_cliente_view,
    solicitar_asesoria_emergencia_view,
    solicitar_asesoria_view,
    solicitar_capacitacion_view,
    solicitar_visita_view,
    transaccion_exitosa_view,
)

app_name = "clientes"
urlpatterns = [
    path("home/", view=home_view, name="home"),
    path("realizar-pago/", view=realizar_pago_view, name="realizar_pago"),
    path("empresa-adeudada/", view=empresa_adeudada_view, name="empresa_adeudada"),
    path(
        "transaccion-exitosa/",
        view=transaccion_exitosa_view,
        name="transaccion_exitosa",
    ),
    path(
        "recepcion-transaccion/",
        view=recepcion_transaccion_view,
        name="recepcion_transaccion",
    ),
    path("reporte-historico/", view=reporte_cliente_view, name="reporte_cliente"),
    path(
        "solicitar-asesoria-emergencia/",
        view=solicitar_asesoria_emergencia_view,
        name="solicitar_asesoria_emergencia",
    ),
    path(
        "solicitar-capacitacion/",
        view=solicitar_capacitacion_view,
        name="solicitar_capacitacion",
    ),
    path(
        "capacitacion/<int:pk>/modificar-participantes/",
        view=modificar_participantes_capacitacion_view,
        name="modificar_participantes_capacitacion",
    ),
    path(
        "solicitar-visita/",
        view=solicitar_visita_view,
        name="solicitar_visita",
    ),
    path(
        "solicitar-asesoria/",
        view=solicitar_asesoria_view,
        name="solicitar_asesoria",
    ),
    path(
        "asesoria/<int:pk>/modificar-multa",
        view=modificar_multa_view,
        name="asesoria_modificar_multa",
    ),
]

no_mas_accidentes/profesionales/urls.py
from django.urls import path

from no_mas_accidentes.profesionales.views import (
    actualizar_actividad_de_mejora_view,
    actualizar_asesoria_emergencia_view,
    actualizar_asesoria_view,
    actualizar_asistencia_capacitacion_view,
    actualizar_capacitacion_view,
    actualizar_checklist_view,
    actualizar_visita_view,
    crear_o_actualizar_checklist_base_view,
    detalle_empresa_informacion_view,
    home_view,
    lista_actividades_mejora_view,
    lista_empresas_asignadas_view,
    lista_servicios_asignados_view,
    revisar_actividad_de_mejora_view,
)

app_name = "profesionales"
urlpatterns = [
    path("home/", view=home_view, name="home"),
    path(
        "empresas-asignadas/lista",
        view=lista_empresas_asignadas_view,
        name="empresas_asignadas_lista",
    ),
    path(
        "empresas-asignadas/<int:pk>/informacion",
        view=detalle_empresa_informacion_view,
        name="empresas_asignadas_detalle_informacion",
    ),
    path(
        "empresas-asignadas/<int:pk>/checklist_base/",
        view=crear_o_actualizar_checklist_base_view,
        name="empresas_asignadas_crear_o_actualizar_checklist_base",
    ),
    path(
        "empresas-asignadas/<int:pk>/actividades-mejora/",
        view=lista_actividades_mejora_view,
        name="empresas_asignadas_actividades_de_mejora",
    ),
    path(
        "servicios/lista",
        view=lista_servicios_asignados_view,
        name="servicios_asignados_lista",
    ),
    path(
        "asesoria-emergencia/<int:pk>/actualizar",
        view=actualizar_asesoria_emergencia_view,
        name="asesoria_emergencia_actualizar",
    ),
    path(
        "capacitacion/<int:pk>/actualizar",
        view=actualizar_capacitacion_view,
        name="capacitacion_actualizar",
    ),
    path(
        "capacitacion/<int:pk>/asistencia",
        view=actualizar_asistencia_capacitacion_view,
        name="capacitacion_actualizar_asistencia",
    ),
    path(
        "visita/<int:pk>/actualizar",
        view=actualizar_visita_view,
        name="visita_actualizar",
    ),
    path(
        "visita/<int:pk>/checklist",
        view=actualizar_checklist_view,
        name="visita_actualizar_checklist",
    ),
    path(
        "visita/<int:pk>/actividad-de-mejora",
        view=actualizar_actividad_de_mejora_view,
        name="visita_actualizar_actividad_mejora",
    ),
    path(
        "asesoria/<int:pk>/actualizar",
        view=actualizar_asesoria_view,
        name="asesoria_actualizar",
    ),
    path(
        "actividad-de-mejora/<int:pk>/revisar/<str:realizado>",
        view=revisar_actividad_de_mejora_view,
        name="revisar_actividad_mejora",
    ),
]

no_mas_accidentes/users/urls.py
from django.urls import path

from no_mas_accidentes.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

no_mas_accidentes/profesionales/forms.py
from collections import Counter

import arrow
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Fieldset, Layout
from django import forms
from django.contrib import messages
from django.core.validators import MaxValueValidator, MinValueValidator
from django.forms import ModelForm, widgets

from no_mas_accidentes.clientes.models import Empresa
from no_mas_accidentes.servicios.models import (
    Checklist,
    OportunidadDeMejora,
    Participante,
    Servicio,
)


class DetalleEmpresaForm(ModelForm):
    class Meta:
        model = Empresa
        fields = (
            "nombre",
            "rut",
            "giro",
            "direccion",
            "telefono",
            "profesional_asignado",
            "esta_activa",
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["direccion"].widget = widgets.TextInput()
        for fieldname in self.fields:
            self.fields[fieldname].disabled = True


class ActualizarAsesoriaEmergenciaForm(ModelForm):
    class Meta:
        model = Servicio
        readonly_fields = (
            "profesional",
            "empresa",
            "agendado_para",
        )
        fields = readonly_fields + (
            "motivo",
            "contenido",
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.terminado = False
        for fieldname in self.Meta.readonly_fields:
            self.fields[fieldname].disabled = True

    def clean(self):
        self.data = self.data.copy()
        if "Finalizar" in self.data:
            self.terminado = True
        else:
            self.terminado = False
        cleaned_data = super().clean()
        return cleaned_data

    def save(self, commit: bool = True):
        asesoria_emergencia = super().save(commit=False)
        if self.terminado:
            asesoria_emergencia.realizado_en = arrow.utcnow().datetime
        asesoria_emergencia.save()
        return asesoria_emergencia


class ActualizarCapacitacionForm(ModelForm):
    class Meta:
        model = Servicio
        readonly_fields = (
            "profesional",
            "empresa",
            "agendado_para",
        )
        fields = readonly_fields + ("motivo", "contenido", "materiales")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.terminado = False
        for fieldname in self.Meta.readonly_fields:
            self.fields[fieldname].disabled = True

    def clean(self):
        self.data = self.data.copy()
        if "Finalizar" in self.data:
            self.terminado = True
        else:
            self.terminado = False
        cleaned_data = super().clean()
        return cleaned_data

    def save(self, commit: bool = True):
        capacitacion = super().save(commit=False)
        if self.terminado:
            capacitacion.realizado_en = arrow.utcnow().datetime
        capacitacion.save()
        return capacitacion


class ActualizarAsistenciaParticipanteCapacitacionForm(ModelForm):
    class Meta:
        model = Participante
        readonly_fields = ("rut", "nombre", "email")
        fields = readonly_fields + ("asiste",)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.terminado = False
        for fieldname in self.Meta.readonly_fields:
            self.fields[fieldname].disabled = True


class ActualizarAsistenciaParticipantesFormSetHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.form_method = "post"
        self.render_required_fields = True
        self.layout = Layout(
            Fieldset("Participante #{{forloop.counter}}"),
            "rut",
            "nombre",
            "email",
            "asiste",
        )


class ActualizarVisitaForm(ModelForm):
    class Meta:
        model = Servicio
        readonly_fields = (
            "profesional",
            "empresa",
            "agendado_para",
        )
        fields = readonly_fields + ("motivo", "contenido", "materiales")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.terminado = False
        for fieldname in self.Meta.readonly_fields:
            self.fields[fieldname].disabled = True

    def clean(self):
        self.data = self.data.copy()
        if "Finalizar" in self.data:
            self.terminado = True
        else:
            self.terminado = False
        cleaned_data = super().clean()
        return cleaned_data

    def save(self, commit: bool = True):
        visita = super().save(commit=False)
        if self.terminado:
            visita.realizado_en = arrow.utcnow().datetime
        visita.save()
        return visita


class ActualizarChecklistForm(forms.Form):
    numero_de_items = forms.IntegerField(
        widget=forms.HiddenInput(),
        validators=[MinValueValidator(3), MaxValueValidator(15)],
    )

    def __init__(self, *args, **kwargs):
        numero_de_items = kwargs.pop("numero_de_items", 3)
        print("numero de items", numero_de_items)
        self.id_servicio = kwargs.pop("id_servicio")
        self.request = kwargs.pop("request")
        super().__init__(*args, **kwargs)
        self.fields["numero_de_items"].initial = numero_de_items
        for index in range(int(numero_de_items)):
            self.fields[f"item_{index+1}"] = forms.CharField(
                min_length=10, max_length=256
            )
            self.fields[f"item_{index+1}_respuesta"] = forms.BooleanField(
                required=False
            )

    def clean(self):
        cleaned_data = self.cleaned_data
        preguntas = list(self.cleaned_data.values())
        preguntas = [
            pregunta for pregunta in preguntas if pregunta not in (False, True, None)
        ]
        items_duplicados = [k for k, v in Counter(preguntas).items() if v > 1]

        if items_duplicados:
            cleaned_data_con_items_duplicados = cleaned_data.copy()
            for k, v in cleaned_data_con_items_duplicados.items():
                if v in items_duplicados:
                    self.add_error(field=k, error="Este item está duplicado")
            messages.warning(
                request=self.request,
                message=f"Existen items duplicados en el checklist: {items_duplicados}",
            )
        return cleaned_data

    def save(self, commit: bool = True):
        cleaned_data = self.cleaned_data.copy()
        cleaned_data.pop("numero_de_items")
        items_nuevos = {}
        for key, value in cleaned_data.items():
            if "item" in key and "respuesta" not in key:
                items_nuevos[value] = cleaned_data[f"{key}_respuesta"]
        checklist = Checklist.objects.get(servicio_id=self.id_servicio)
        if checklist.items == items_nuevos:
            messages.info(
                request=self.request,
                message="Los items a actualizar son iguales a los anteriores, no se ha actualizado el checklist.",
            )
            return
        messages.success(request=self.request, message="Se ha actualizado el checklist")
        checklist.items = items_nuevos
        checklist.save()
        return checklist


class ActualizarOportunidadDeMejoraVisitaForm(ModelForm):
    class Meta:
        model = OportunidadDeMejora
        fields = ("contenido",)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.terminado = False
        for fieldname in self.fields:
            self.fields[fieldname].required = True


class ActualizarOportunidadDeMejoraVisitaFormSetHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.form_method = "post"
        self.render_required_fields = True
        self.layout = Layout(
            Fieldset("Actividad de mejora #{{forloop.counter}}"), "contenido"
        )


class ActualizarAsesoriaFiscalizacionForm(ModelForm):
    class Meta:
        model = Servicio
        readonly_fields = (
            "profesional",
            "empresa",
            "agendado_para",
        )
        fields = readonly_fields + (
            "motivo",
            "contenido",
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.terminado = False
        for fieldname in self.Meta.readonly_fields:
            self.fields[fieldname].disabled = True

    def clean(self):
        self.data = self.data.copy()
        if "Finalizar" in self.data:
            self.terminado = True
        else:
            self.terminado = False
        cleaned_data = super().clean()
        return cleaned_data

    def save(self, commit: bool = True):
        asesoria_fiscalizacion = super().save(commit=False)
        if self.terminado:
            asesoria_fiscalizacion.realizado_en = arrow.utcnow().datetime
        asesoria_fiscalizacion.save()
        return asesoria_fiscalizacion

no_mas_accidentes/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

no_mas_accidentes/templates/profesionales/visita/actividades_de_mejora.html
{% extends 'profesionales/visita/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block nav_item_actividades_de_mejora %}active{% endblock %}
{% block detalle %}
<div class="card-body col-lg-12 mt-5">
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {% crispy formset helper %}
        </table>

        <div class="d-flex flex-wrap gap-4 justify-content-end">
            <input type="submit" class="btn btn-primary waves-effect waves-light" value="Modificar actividades">
            <input type="submit" class="btn btn-danger waves-effect waves-light" onclick="window.location='{% url 'profesionales:home' %}'; return false;" value="Cancelar">
        </div>
    </form>

</div>
{% endblock %}

no_mas_accidentes/templates/profesionales/visita/actualizar.html
{% extends 'profesionales/visita/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block nav_item_general %}active{% endblock %}
{% block detalle %}
<div class="card-body col-lg-12 mt-5">
     <form action="" method="post">
          {% csrf_token %}

          {% for error in form.non_field_errors %}
              {{ error }}
          {% endfor %}

          <div class="row">
              {{ form|crispy }}
          </div>

          <div class="d-flex flex-wrap gap-4 justify-content-end">
              <input type="submit" class="btn btn-primary waves-effect waves-light" name="Actualizar" value="Actualizar">
              <input type="submit" class="btn btn-danger waves-effect waves-light" name="Finalizar" value="Finalizar">

          </div>
      </form>
</div>
{% endblock %}

no_mas_accidentes/templates/profesionales/visita/actualizar_checklist.html
{% extends 'profesionales/visita/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block nav_item_checklist %}active{% endblock %}
{% block detalle %}
<div class="card-body col-lg-12 mt-5">
    <h4>Número mínimo de items: 3</h4>
    <h4>Número máximo de items: 15</h4>
    <form action="" method="post">
        {% csrf_token %}

        {% for error in form.non_field_errors %}
            {{ error }}
        {% endfor %}

        <div id="form-wrapper" class="row">
            {% for field in form %}
              <div>{{ field|as_crispy_field }}</div>
            {% endfor %}
        </div>
        <div class="d-flex flex-wrap gap-4 justify-content-end">
            <button type="button" id="eliminar-item-extra" class="btn btn-danger">Eliminar último item</button>
            <button type="button" id="agregar-item-extra" class="btn btn-secondary">Agregar nuevo item</button>
            <input type="submit" class="btn btn-primary waves-effect waves-light" value="Actualizar">
        </div>
    </form>
</div>
{% endblock %}


{% block extra_javascript %}
<script>
let form_count = Number($('#id_numero_de_items').val());
console.log(form_count)
$("#agregar-item-extra").click(function() {
    if (form_count === 15){
      return
    }
    form_count ++;

    let element_html = `
       <div>
          <div id="div_id_item_${form_count}" class="mb-3">
             <label for="id_item_${form_count}" class="form-label requiredField">
             Item ${form_count}<span class="asteriskField">*</span>
             </label>
             <input type="text" name="item_${form_count}" value="" maxlength="256" minlength="10" class="textinput textInput form-control" required="" id="id_item_${form_count}">
          </div>
       </div>
       <div>
            <div class="mb-3">
                <div id="div_id_item_${form_count}_respuesta" class="mb-3">
                    <input type="checkbox" name="item_${form_count}_respuesta" class="checkboxinput form-check-input" id="id_item_${form_count}_respuesta">
                    <label for="id_item_${form_count}_respuesta" class="form-check-label">
                        Item ${form_count} respuesta
                    </label>
                </div>
            </div>
       </div>
    `
    let element = $(element_html);
    $("#form-wrapper").append(element);

    $("[name=numero_de_items]").val(form_count);
})

$("#eliminar-item-extra").click(function() {
    if (form_count === 3){
      return
    }
    $(`#div_id_item_${form_count}`).remove();
    $(`#div_id_item_${form_count}_respuesta`).parent().remove();
    $("[name=numero_de_items]").val(form_count);
    form_count --;

})
</script>
{% endblock %}

no_mas_accidentes/templates/profesionales/visita/base.html
{% extends 'profesionales/base.html' %}

{% load static %}
{% block contents %}
<div class="row">
    <div class="col-lg-12">
        <div class="col-sm-12 d-print-none">
            <div class="text-sm-start">
                <a type="button" class="btn btn-success btn-rounded waves-effect waves-light mb-2 me-2" href="{% url 'profesionales:servicios_asignados_lista' %}"><i class="mdi mdi-backburger me-1"></i>Volver al listado de actividades asignadas</a>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <ul class="nav nav-tabs d-print-none" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link {% block nav_item_general %}{% endblock %}"  href="{% url 'profesionales:visita_actualizar' pk=object.pk %}" role="tab">
                            <span class="d-block d-sm-none"><i class="fas fa-address-card"></i></span>
                            <span class="d-none d-sm-block">General</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% block nav_item_checklist %}{% endblock %}" href="{% url 'profesionales:visita_actualizar_checklist' pk=object.pk %}" role="tab">
                            <span class="d-block d-sm-none"><i class="fas fa-chalkboard-teacher"></i></span>
                            <span class="d-none d-sm-block">Checklist</span>
                        </a>
                    </li>
                  <li class="nav-item">
                        <a class="nav-link {% block nav_item_actividades_de_mejora %}{% endblock %}" href="{% url 'profesionales:visita_actualizar_actividad_mejora' pk=object.pk %}" role="tab">
                            <span class="d-block d-sm-none"><i class="bx bx-list-check"></i></span>
                            <span class="d-none d-sm-block">Actividades de mejora</span>
                        </a>
                    </li>
                </ul>
                {% block detalle %}
                {% endblock %}

            </div>
        </div>
    </div>
</div>
{% endblock %}